services:
  # NodeJS/Express service
  app_be:
    container_name: app_backend
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: dev
    depends_on:
      - app_db
    ports:
      - "3009:3009"
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - ./server/src:/app/src

  # Postgres service
  app_db:
    container_name: app_db
    image: postgres:15.4-alpine3.18
    ports:
      - "54321:5432"
    env_file:
      - .env
    volumes:
      - ./server/pg-data:/var/lib/postgresql/data
      - ./server/config/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - app_network

  # Nginx/Vue.js service
  app_fe:
    container_name: app_frontend_dev
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "82:82"
    volumes:
      - ./client:/app

networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16